name: EveryoneGetsDiscount
version: 1.0.1
main: io.github.fr4ncyilgrande.everyonegetsdiscount.EveryoneGetsDiscount
api-version: "26.1.2"
load: POSTWORLD
description: Shares the discounts from zombie villager curing with online players
