name: EveryoneGetsDiscount
version: ${version}
main: io.github.fr4ncyilgrande.everyonegetsdiscount.EveryoneGetsDiscount
api-version: "26.1.2"
load: POSTWORLD
description: Condivide gli sconti da cura del villager zombificato con i giocatori online
