name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:25-jdk

    steps:
      - uses: actions/checkout@v5

      - name: Verify Java version
        run: java -version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle (forced Java 25)
        run: gradle clean build -Dorg.gradle.java.home=$JAVA_HOME

      - name: Upload JAR
        uses: actions/upload-artifact@v5
        with:
          name: my-app-jar
          path: build/libs/*.jar
