name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Java 25 (Early Access)
        uses: actions/setup-java@v5
        with:
          java-version: '25-ea'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: gradle clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v5
        with:
          name: EveryoneGetsDiscount
          path: build/libs/*.jar
