name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:25-jdk

    steps:
      - uses: actions/checkout@v5

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v5
        with:
          name: my-app-jar
          path: build/libs/*.jar
